### PR TITLE
CoreXY

### PR DESCRIPTION
**Pull request by PatrikTheDev**

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Hi @Patrik-svobodik ,

thanks for the pull request.
But as this is a complete different motion system it doesn't makes sense do merge it with the MK3-private_build branch. It would make sense to create another branch for that motion system.
Did you build your own CoreXY version of the Prusa i3 MK3 parts? Does this firmware works, as i thought that Prusa removed a lot of CoreXY code time ago due to hitting limits and to 'cleanup' the code.

**Comment by PatrikTheDev** [comment]
Hi, I am working on it, for now it homes (even sensorlessly) but it does not respect gcodes, I am going to port marlin’s code into PFW, but it will take some time

**Comment by PatrikTheDev** [comment]
It would be good idea to make a separate branch for it

**Comment by 3d-gussner** [comment]
Close this pull request due no interaction anymore.

**Pull request closed without merging**
