### PR TITLE
Add line to Runout Sensor to fix inverting sensor.

### PR DESCRIPTION
**Pull request by TheZeroBeast**
Tested and working with false set on const bool FR_SENS_INVERTING with opto endstop.

Let me know if you have any questions mate.

Look forward to more of your good work.

Rob

### CODE REVIEW

**Comment by 3d-gussner** [comment]
Thanks. I just saw the semicolon mistake :-)

But there is an issue: Some filament sensors work with Signal to Ground and other Signal to VCC...
So we will need 3 version of firmware:
1st normal
2nd filament sensor S to GND
3rd filament sensor S to VCC

Guess best would be additional LCD menu under settings, something like:
- FilSens    [ON]/[OFF]
- FilSens [normal]/[invert]

So it would be ONE firmware version where the user can activate and invert the filament runout sensor as needed.

**Comment by TheZeroBeast** [comment]
Hey Mate,

Yeah, no problem.
The idea of having it user selectable is a grand one to accommodate the different sensors options.

I’m rusty as hell with code but I’ll take a look when I have some time.

Rob

**Comment by 3d-gussner** [comment]
Hey Rob,

same here ... coding is rusty...
Started to implement the LCD menu under Settings but have some issues with switching between the modes :-(
check https://github.com/3d-gussner/Prusa-Firmware/tree/MK2-FR_SENS-MENU

**Comment by 3d-gussner** [comment]
@TheZeroBeast Nice design on Thingiverse

**Comment by 3d-gussner** [comment]
@TheZeroBeast Hi how are you? Thanks for the pull request, used it in this release!
I was bit busy with the filament run out sensor menu and hope got everything fixed. It would be great if you could check the https://github.com/3d-gussner/Prusa-Firmware/commit/6b18f434995af0ae42915462df5d2677a786e41f and the https://github.com/3d-gussner/Prusa-Firmware/releases/tag/v3.0.12-3

**Comment by TheZeroBeast** [comment]
Hey mate,

I spent some time today on getting a settings submenu setup for FR and a few EEPROM variables to save the values.

I'll check out your code soon.

Good work

Regards,
Robert McKenzie

**Comment by 3d-gussner** [comment]
@TheZeroBeast got somewhere between two steps a bug...have to configure out what it is.
Cannot see it now...have to take a break...sometimes you just don't see it anymore

**Comment by 3d-gussner** [comment]
@TheZeroBeast maybe you find the bug.
What is working fine:
- LCD menu
- As soon the sensors option is deactivated it works like with default Prusa firmware
What is not working:
- As soon i activate the sensor, no matter which sensor type i choose it goes immediately in filament change mode...worked one or two versions before for the 'S to GND' but after adding 'S to VCC' to the Marlin_main.cpp ifdef FILAMENT_RUNOUT_SUPPORT everything went wrong
- Think my problem is there and getting the right FR_SENS_INVERTING ... 'S to GND' == false or true

Cannot solve it now...leave it until later or tomorrow.

**Comment by TheZeroBeast** [comment]
Hi Gussner,





I haven't had time to test but I have made a change below to marlin_main.cpp to manage the inv and pin states.





I took out the first "if" statement and added it to the second regarding state with inversion.





My understanding of the rambo input PIN we're using is that in is a digital PIN with state == LOW when PIN is <1.5v and state == HIGH when PIN is >3.5v.


In the middle ground there is an invalid PIN voltage.





With a mechanical switch between GND and PIN in an open state the Pull-up resistor needs to be enabled to pull PIN to HV rail and a state == HIGH.


Closing the switch pulls PIN to GND and a state == LOW.





That's all sweet.




Right, if a mechanical switch between HV Rail and PIN is open it needs an external 10kR Pull-down resister to GND to ensure PIN isn't floating as there's no Internal Pull-down.





So to me we need a third setting for the FIlament Runout Sensor, the three being:





Filament Runout Sensor [ON/OFF]


INVERTING [ON/OFF]


Pull-up Res [ON/OFF]





This brings me to my next investigation into simple reprap opto endstop for the uses here.





If the photo transistor is fully off, i.e. beam is completely broken by a opaque object then PIN is Pulled to HV to give us a state == HIGH.





If however the object isn't fully opaque then the transistor is only turned off as much as it can block the beam and state == HIGH isn't reached.


This happens so much when attempting to sense filament that it's almost unusable in this state.





My solution, (which I'm yet to test, definately will have time to do so this weekend) is two steps.





Step 1: Modify activation code as below to accept HIGH and everything else as the two states.


By doing this we can still utilise mechanical switches as before but for opto switches we can have a switch setup to by sensitive to the >3.5v HIGH state.





Step2: Is to have the opto adjusted/modified with a single resistor, calculated to have to beam broken state biased just shy of 3.5v. I have one setup ready to test biased to 3.4v with a test POT.





By doing this even clear filament is able to break the beam enough to through a state == HIGH.





I'll keep you informed on this front.





I have also fixed up the lcd code(ultralcd.cpp) that displays the FR_SENS in endstops menu sot that it reflects states and incorporates inversion.





Let me know if you see any issues, like I said the other day, a bit rusty, we'll get there though, awesome work so far.





#####################################################################################

ultralcd.cpp






// FR_SENS

 if (fr_sens_active == true) {

      lcd.setCursor(4, 1);

      lcd_printPGM(((digitalRead(FR_SENS) == HIGH) != FR_SENS_INVERTING) ? (PSTR("FR_S OK")) : (PSTR("FR_S NO")));

}

// end FR_SENS 

#####################################################################################







#####################################################################################



MARLIN_MAIN.cpp





#ifdef FILAMENT_RUNOUT_SUPPORT

           if (fr_sens_active &&((digitalRead(FR_SENS) == HIGH) != FR_SENS_INVERTING)) {

                       feedmultiplyBckp=feedmultiply;

                       float target[4];

                       float lastpos[4];

                       target[X_AXIS]=current_position[X_AXIS];

                       target[Y_AXIS]=current_position[Y_AXIS];

                       target[Z_AXIS]=current_position[Z_AXIS];

                       target[E_AXIS]=current_position[E_AXIS];

                       lastpos[X_AXIS]=current_position[X_AXIS];

                       lastpos[Y_AXIS]=current_position[Y_AXIS];

                       lastpos[Z_AXIS]=current_position[Z_AXIS];

                       lastpos[E_AXIS]=current_position[E_AXIS];

                       //retract by E

                        

                       target[E_AXIS]+= FILAMENTCHANGE_FIRSTRETRACT ;

                        

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 400, active_extruder);

 

 

                        target[Z_AXIS]+= FILAMENTCHANGE_ZADD ;

 

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 300, active_extruder);

 

                       target[X_AXIS]= FILAMENTCHANGE_XPOS ;

                      

                       target[Y_AXIS]= FILAMENTCHANGE_YPOS ;

                         

                 

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 70, active_extruder);

 

                       target[E_AXIS]+= FILAMENTCHANGE_FINALRETRACT ;

                          

 

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 20, active_extruder);

 

                       //finish moves

                       st_synchronize();

                       //disable extruder steppers so filament can be removed

                       disable_e0();

                       disable_e1();

                       disable_e2();

                      delay(100);

                        

                       //LCD_ALERTMESSAGEPGM(MSG_FILAMENTCHANGE);

                       uint8_t cnt=0;

                       int counterBeep = 0;

                       lcd_wait_interact();

                        while(!lcd_clicked()){

                         cnt++;

                         manage_heater();

                         manage_inactivity(true);

                         //lcd_update();

                         if(cnt==0)

                         {

                         #if BEEPER > 0

                          

                           if (counterBeep== 500){

                             counterBeep = 0;

                              

                           }

                          

                            

                           SET_OUTPUT(BEEPER);

                           if (counterBeep== 0){

                             WRITE(BEEPER,HIGH);

                           }

                          

                           if (counterBeep== 20){

                             WRITE(BEEPER,LOW);

                           }

                            

                            

                            

                          

                            counterBeep++;

                         #else

                     #if !defined(LCD_FEEDBACK_FREQUENCY_HZ) || !defined(LCD_FEEDBACK_FREQUENCY_DURATION_MS)

                             lcd_buzz(1000/6,100);

                     #else

                       lcd_buzz(LCD_FEEDBACK_FREQUENCY_DURATION_MS,LCD_FEEDBACK_FREQUENCY_HZ);

                     #endif

                         #endif

                         }

                       }

                        

                       WRITE(BEEPER,LOW);

                        

                       target[E_AXIS]+= FILAMENTCHANGE_FIRSTFEED ;

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 20, active_extruder); 

                        

                        

                       target[E_AXIS]+= FILAMENTCHANGE_FINALFEED ;

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 2, active_extruder); 

                        

                 

                        

                        

                        

                       lcd_change_fil_state = 0;

                       lcd_loading_filament();

                       while ((lcd_change_fil_state == 0)||(lcd_change_fil_state != 1)){

                        

                         lcd_change_fil_state = 0;

                         lcd_alright();

                         switch(lcd_change_fil_state){

                          

                            case 2:

                                     target[E_AXIS]+= FILAMENTCHANGE_FIRSTFEED ;

                                     plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 20, active_extruder); 

                        

                        

                                     target[E_AXIS]+= FILAMENTCHANGE_FINALFEED ;

                                     plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 2, active_extruder); 

                                      

                                     

                                     lcd_loading_filament();

                                     break;

                             case 3:

                                    target[E_AXIS]+= FILAMENTCHANGE_FINALFEED ;

                                     plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 2, active_extruder); 

                                     lcd_loading_color();

                                     break;

                                          

                             default:

                                     lcd_change_success();

                                     break;

                         }

                          

                       }

                        

 

                        

                     target[E_AXIS]+= 5;

                     plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 2, active_extruder);

                        

                     target[E_AXIS]+= FILAMENTCHANGE_FIRSTRETRACT;

                     plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 400, active_extruder);

                        

 

                       //current_position[E_AXIS]=target[E_AXIS]; //the long retract of L is compensated by manual filament feeding

                       //plan_set_e_position(current_position[E_AXIS]);

                       plan_buffer_line(target[X_AXIS], target[Y_AXIS], target[Z_AXIS], target[E_AXIS], 70, active_extruder); //should do nothing

                       plan_buffer_line(lastpos[X_AXIS], lastpos[Y_AXIS], target[Z_AXIS], target[E_AXIS], 70, active_extruder); //move xy back

                       plan_buffer_line(lastpos[X_AXIS], lastpos[Y_AXIS], lastpos[Z_AXIS], target[E_AXIS], 200, active_extruder); //move z back

                        

                        

                       target[E_AXIS]= target[E_AXIS] - FILAMENTCHANGE_FIRSTRETRACT;

                        

                      

                             

                       plan_buffer_line(lastpos[X_AXIS], lastpos[Y_AXIS], lastpos[Z_AXIS], target[E_AXIS], 5, active_extruder); //final untretract

                        

                        

                       plan_set_e_position(lastpos[E_AXIS]);

                        

                       feedmultiply=feedmultiplyBckp;

                        

                     

                        

                       char cmd[9];

 

                       sprintf_P(cmd, PSTR("M220 S%i"), feedmultiplyBckp);

                       enquecommand(cmd);

 

 

 

           }

       #endif

#####################################################################################







 

Regards,
Robert McKenzie


On 10 Aug, 2017, at 11:23 PM, 3d-gussner <notifications@github.com> wrote:






@TheZeroBeast maybe you find the bug.
 What is working fine:
LCD menu
As soon the sensors option is deactivated it works like with default Prusa firmware
 What is not working:
As soon i activate the sensor, no matter which sensor type i choose it goes immediately in filament change mode...worked one or two versions before for the 'S to GND' but after adding 'S to VCC' to the Marlin_main.cpp ifdef FILAMENT_RUNOUT_SUPPORT everything went wrong
Think my problem is there and getting the right FR_SENS_INVERTING ... 'S to GND' == false or true

Cannot solve it now...leave it until later or tomorrow.

**Pull request closed without merging**
