### PR TITLE
Update SK translation

### PR DESCRIPTION
**Pull request by ingbrzy**

### CODE REVIEW

**Comment by ingbrzy** [comment]
@shatter136 please approve

**Review by shatter136 — APPROVED** [review]
nicely done

**Comment by 3d-gussner** [comment]
@ingbrzy Can you please make this PR to prusa3d/MK3? And if you can also the cherry-pick to MK3_3.12?

**Comment by ingbrzy** [comment]
> @ingbrzy Can you please make this PR to prusa3d/MK3? And if you can also the cherry-pick to MK3_3.12?

Sorry, I am not able to do that.. can you push it by yourself?

**Comment by 3d-gussner** [comment]
Thanks I commit these changes directly to the PRs

**Comment by 3d-gussner** [comment]
Thanks for the PR ported these changes to different PR

**Pull request closed without merging**
