### PR TITLE
Filament Runout Menu Settings (tested on OPTO)

### PR DESCRIPTION
**Pull request by TheZeroBeast**
Hi Gussner,

I have gone through and simplified the inverting code, added a setting to enable internal pullup resistor for S to GND without external ones.

Tested enable, disable and inverting successfully with prints in between with runouts events to test it is definitely off and so on.

I have also done PID 8 stage cals on default MK2S hardware which should be a nit nicer to start with for most people. Not to say you couldn't keep a hex with your specific ones.

P.S. Do you have details on how you did the cork mod, it sounds like a great idea?

I also found that the digital input changes to high when PIN above 2.5v witch can be configured with a simple resistor change on the riprap opto. I'll do up a guide for the item on thingiverse.

Talk to you soon,
Rob

### CODE REVIEW

**Comment by 3d-gussner** [comment]
@TheZeroBeast Hey Rob,
thanks a lot for helping, I will check your code.
Few days ago i saw the filament runout solution in Marlin and guess will try to get closer to it...just few things like 'FR_SENS' in pins.h is 'FIL_RUNOUT_PIN' and so on 'FIL_RUNOUT_INVERTING', 'ENDSTOPPULLUP_FIL_RUNOUT'. Hope that makes it easier in the future to implement updates done in Marlin.

The cork helps with the heated bed as the E3d silocone sock helps the hotend. Best is to watch the video of Nillabean Prusa - Cork Edition - Insulating the Heatbed....quite long but you don't need to watch the hole 3+h ...
https://www.youtube.com/watch?v=DD_pWGp8Ubo

I will post the source code and hex files with the default PID values, and change it for me. In the beginning it was just a github for me and i liked to have my settings in the firmware defaults. But time changes and more and more people are downloading it and so going back to Prusa defaults makes sense.

**Comment by 3d-gussner** [comment]
@TheZeroBeast Question:
Don't we need the pullup only when using 'S to GND'? I guess all 'S to VCC' will have a pullup resistor, or not? I could not find any mechanical filament runout sensors 'S to GND' which have a pullup resistor, also not really needed.
So we didn't need an additional eeprom entry, just using arduino pullup when it is 'S to GND' and 'normal' with 'S to VCC'.

What do you think?

**Comment by 3d-gussner** [comment]
@TheZeroBeast Why do you you have a different ultralcd.cpp in the root?

**Comment by TheZeroBeast** [comment]
Hey Gussner,

The ultralcd.cpp in root was supposed to be uploaded to firmware folder and already has the menu only show pullup for the S to GND option. Uploaded to the wrong folder sorry.

So yes to your next message👍

Yeah, sounds good, we can probably tidy the code up a bit when modifying variables.

I don't see why this wouldn't be an awesome feature for the main firmware, have you thought about putting in a pull request back up the line?

Regards,
Robert McKenzie

**Comment by 3d-gussner** [comment]
Hi Robert,

i feel bit guilty...wasn't so busy with the coding last days. Thanks a lot!

**Comment by 3d-gussner** [comment]
@TheZeroBeast Hi Robert,

i did some changes. If you like check out 
https://github.com/3d-gussner/Prusa-Firmware/commit/754e7414f529e058abc800237d329f112ea8a72e#diff-a940a548ba41bc988f99d51fd02f21de
https://github.com/3d-gussner/Prusa-Firmware/commit/f4e2d664de8156fa3993567eccf7cbf9290ee1c4#diff-a940a548ba41bc988f99d51fd02f21de
https://github.com/3d-gussner/Prusa-Firmware/commit/62bb56985cb1a8e95e6ba7a9deb70c5cf563f987#diff-a940a548ba41bc988f99d51fd02f21de

**Pull request merged**
